### ISSUE TITLE
please add support for godaddy api /v2/customers/{customerId}/certificates

### ISSUE THREAD

**Issue by robdew** [turbot/steampipe-plugin-godaddy#21]
**Is your feature request related to a problem? Please describe.**
With the current tables you cannot list all certificates for a customer account.  This *might* be because the plugin only supports v1 of the godaddy API? V2 of the API adds a new method to get all certificates for a given customerId

https://developer.godaddy.com/doc/endpoint/certificates#/

**Describe the solution you'd like**
I would like to use this plugin to get all the certificate details for all certificates, not just a particular certificateId

**Describe alternatives you've considered**
Hitting the API directly from Python instead of Steampipe.

**Additional context**
![Screenshot 2024-06-05 at 4 03 12 PM](https://github.com/turbot/steampipe-plugin-godaddy/assets/3137089/2d061d4e-c52c-409e-b941-21e57f23f996)

**Comment by ParthaI** [comment]
Hello @robdew,

Thank you for bringing this issue to our attention. I have updated the `godaddy_certificate` table to list out the certificates by customer ID and have pushed the changes to the `issue-21` branch.

Unfortunately, I wasn't able to test it in our environment due to limited permissions.

If you could test it in the PR branch `issue-21` and share your feedback, it would be greatly appreciated.

Steps to build the plugin from the branch `issue-21`:

- Clone the repository: git clone https://github.com/turbot/steampipe-plugin-godaddy.git
- Navigate to the plugin directory: cd steampipe-plugin-godaddy
- Checkout the branch: git checkout `issue-21`
- Build the plugin: make
- Run the query.

Thanks!

**Comment by robdew** [comment]
I have been working on this but cannot make the latest release of the plugin work correctly either.

At this point the best I can offer is that this query:
```
select
  common_name,
  status,
  certificate_id,
  serial_number,
  created_at,
  valid_start,
  valid_end
from
  godaddy_certificate
where
  certificate_id = 'redacted';
```

Generates no results (that's not expected) with the latest release version of the plugin, but with the `issue-2` release I get this additional error:

```
Error: godaddy: table 'godaddy_certificate' column 'contact' requires hydrate data from getCertificate but none is available.
 (SQLSTATE HV000)
```

**Comment by ParthaI** [comment]
Hello @robdew, apologies for the late response.

Were you able to query the table from the `issue-21` branch by following the steps mentioned [here](https://github.com/turbot/steampipe-plugin-godaddy/issues/21#issuecomment-2272978475)?

In this PR, we added support for listing all certificates for a customer by specifying the `customer_id` in the `WHERE` clause (e.g., `where customer_id = '295e3bc3-b3b9-4d95-aae5-ede41a994d13'`).

Regarding the error you mentioned, it does seem unusual. I’ve pushed another commit to the `issue-21` branch that handles the `not found` error code. Could you please pull the latest changes and try running the following query again after rebuilding the code?

```sql
select
  common_name,
  status,
  certificate_id,
  serial_number,
  created_at,
  organization,
  root_type,
  valid_start,
  valid_end,
  revoked_at
from
  godaddy_certificate
where
  customer_id = '295e3bc3-b3b9-4d95-aae5-ede41a994d13'
```
